name: telegram message
on: 
  release:
    types: [released]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} 发布了新版本: ${{ github.event.release.name }}
            发布内容: ${{ github.event.release.body }}
            仓库: ${{ github.repository }}
            链接: ${{ github.event.release.html_url }}
